/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import Negocio.Copetran;
import java.text.SimpleDateFormat;
import java.util.ArrayList;


/**
 *
 * @author GAMEMAX
 */
public class FormVenta extends javax.swing.JFrame {
    private Copetran myVentas;
    private javax.swing.JButton[] botonesAsientos;
    
    public FormVenta(Copetran fv) {
        initComponents();
        this.myVentas = fv;
        cargarSalidas(this.myVentas.salidasFechaDestino());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAsientos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmdSalidaSeleccion = new javax.swing.JComboBox<>();
        cmbMostrarPuestos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cmdSalidaSeleccion1 = new javax.swing.JComboBox<>();
        cmbMostrarPuestos1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmdSalidaSeleccion2 = new javax.swing.JComboBox<>();
        cmbMostrarPuestos2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VENTAS");

        javax.swing.GroupLayout panelAsientosLayout = new javax.swing.GroupLayout(panelAsientos);
        panelAsientos.setLayout(panelAsientosLayout);
        panelAsientosLayout.setHorizontalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1287, Short.MAX_VALUE)
        );
        panelAsientosLayout.setVerticalGroup(
            panelAsientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VENTA - CANCELACION - REPROGRAMACION ");
        jLabel1.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("ESCOGER SALIDA :");

        cmdSalidaSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una salida..." }));

        cmbMostrarPuestos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbMostrarPuestos.setText("CARGAR PUESTOS");
        cmbMostrarPuestos.addActionListener(this::cmbMostrarPuestosActionPerformed);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("MOSTRAR INFO. DE LA SALIDA");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("INFORMACION :");

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("CANCELACION :");

        cmdSalidaSeleccion1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una salida..." }));

        cmbMostrarPuestos1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbMostrarPuestos1.setText("CARGAR PUESTOS");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("MOSTRAR INFO. DE LA SALIDA");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("REPROGRAMACION :");

        cmdSalidaSeleccion2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una salida..." }));

        cmbMostrarPuestos2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbMostrarPuestos2.setText("CARGAR PUESTOS");

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setText("MOSTRAR INFO. DE LA SALIDA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(cmdSalidaSeleccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbMostrarPuestos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(cmdSalidaSeleccion1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbMostrarPuestos1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(cmdSalidaSeleccion2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbMostrarPuestos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3))
                                .addGap(130, 130, 130)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(panelAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 61, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAsientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdSalidaSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbMostrarPuestos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmdSalidaSeleccion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbMostrarPuestos2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton3))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmdSalidaSeleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cmbMostrarPuestos1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2))))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbMostrarPuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMostrarPuestosActionPerformed
        // TODO add your handling code here:
        this.txtMostrar.setText("");
        if(this.cmdSalidaSeleccion.getSelectedItem().equals("Seleccione una salida...")){
            this.txtMostrar.setText("DEBE INGRESAR UNA SALIDA");
        }
        
        String texto = this.cmdSalidaSeleccion.getSelectedItem().toString();
        int capacidadBus = this.myVentas.obtenerCapacidad(texto);
        dibujarMapaAsientos(texto,capacidadBus);
        
    }//GEN-LAST:event_cmbMostrarPuestosActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbMostrarPuestos;
    private javax.swing.JButton cmbMostrarPuestos1;
    private javax.swing.JButton cmbMostrarPuestos2;
    private javax.swing.JComboBox<String> cmdSalidaSeleccion;
    private javax.swing.JComboBox<String> cmdSalidaSeleccion1;
    private javax.swing.JComboBox<String> cmdSalidaSeleccion2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelAsientos;
    private javax.swing.JTextArea txtMostrar;
    // End of variables declaration//GEN-END:variables

    private void cargarSalidas(ArrayList<String> salidasFechaDestino) {
        this.cmdSalidaSeleccion.removeAllItems();
        this.cmdSalidaSeleccion.addItem("Seleccione aqui...");
        
        SimpleDateFormat fecha = new SimpleDateFormat("dd/MM/yyyy HH:mm");
        
        for (int i = 0; i < salidasFechaDestino.size(); i++) {
            cmdSalidaSeleccion.addItem(salidasFechaDestino.get(i));
        }
    }
    
    private void dibujarMapaAsientos(String textoCombo, int capacidadBus){
        panelAsientos.removeAll();
        botonesAsientos = new javax.swing.JButton[capacidadBus+1];
        int columnas = (int) Math.ceil((double)capacidadBus/4);
        panelAsientos.setLayout(new java.awt.GridLayout(5, columnas, 10, 10));
        panelAsientos.setPreferredSize(new java.awt.Dimension(780, 200));
        panelAsientos.setSize(new java.awt.Dimension(780, 200));
        int[][] matrizAsientos = new int[5][columnas];
        int contadorAsientos = 1;
        
        for (int c = 0; c < columnas; c++) {
            for (int f = 0; f < 5; f++) {
                if(f == 2){
                    matrizAsientos[f][c] = -2;
                }else if(contadorAsientos <= capacidadBus){
                    matrizAsientos[f][c] = contadorAsientos;
                    contadorAsientos++;
                }else{
                    matrizAsientos[f][c]= -1;
                }
            }
        }
        
        for (int f = 0; f < 5; f++) {
            for (int c = 0; c < columnas; c++) {
                int numeroAsiento = matrizAsientos[f][c];
                if(numeroAsiento == -2){
                    javax.swing.JLabel pasillo= new javax.swing.JLabel("");
                    panelAsientos.add(pasillo);
                    continue;
                }
                if(numeroAsiento == -1){
                    javax.swing.JLabel espacioVacio = new javax.swing.JLabel("");
                    panelAsientos.add(espacioVacio);
                    continue;
                }
                botonesAsientos[numeroAsiento]=new javax.swing.JButton(String.valueOf(numeroAsiento));
                
                if(this.myVentas.verificarEstado(textoCombo, numeroAsiento)){
                    botonesAsientos[numeroAsiento].setBackground(java.awt.Color.RED);
                    botonesAsientos[numeroAsiento].setForeground(java.awt.Color.WHITE);
                    botonesAsientos[numeroAsiento].setEnabled(true);
                }else{
                    botonesAsientos[numeroAsiento].setBackground(java.awt.Color.GREEN);
                    botonesAsientos[numeroAsiento].setForeground(java.awt.Color.BLACK);
                    
                    final int asientoActual = numeroAsiento;
                    botonesAsientos[numeroAsiento].addActionListener(new java.awt.event.ActionListener() {
                    @Override
                    public void actionPerformed(java.awt.event.ActionEvent e) {
                        if(botonesAsientos[asientoActual].getBackground() == java.awt.Color.GREEN){
                            botonesAsientos[asientoActual].setBackground(java.awt.Color.BLUE);
                            botonesAsientos[asientoActual].setForeground(java.awt.Color.WHITE);
                        }else if(botonesAsientos[asientoActual].getBackground() == java.awt.Color.BLUE){
                            botonesAsientos[asientoActual].setBackground(java.awt.Color.GREEN);
                            botonesAsientos[asientoActual].setForeground(java.awt.Color.BLACK);
                        }
                    }
                 });
                }panelAsientos.add(botonesAsientos[numeroAsiento]);
            } 
        }
        panelAsientos.revalidate();
        panelAsientos.repaint();
    } 
}
