/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Negocio.Copetran;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;


/**
 *
 * @author GAMEMAX
 */
public class FormAdmin extends javax.swing.JFrame {
    private Copetran myCopetran;
    
    public FormAdmin(Copetran fa) {
        initComponents();
        this.myCopetran = fa;
        cargarBuses(this.myCopetran.placaBuses());
        cargarRutas(this.myCopetran.destinoRutas());
        cargarConductores(this.myCopetran.nombresConductores());
        limpiarConductor();
        limpiarRuta();
        this.jsFechaHora.setEditor(new javax.swing.JSpinner.DateEditor(this.jsFechaHora, "dd/MM/yyyy HH:mm"));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmdRegistrarBus = new javax.swing.JButton();
        txtPlaca = new javax.swing.JTextField();
        cmbTipoServicio = new javax.swing.JComboBox<>();
        cmdRegistrarRuta = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDestino = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtTarifa = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        cmdRegistrarSalida = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cmbElegirBus = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        cmbConductorElegir = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmdRegistrarConductor = new javax.swing.JButton();
        txtNombreConductor = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtExp = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        txtCorreoConductor = new javax.swing.JTextField();
        txtCedulaConductor = new javax.swing.JTextField();
        txtCelularConductor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbElegirRuta = new javax.swing.JComboBox<>();
        cmdListar = new javax.swing.JButton();
        cmbListas = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        cmdCambiarEstado = new javax.swing.JButton();
        txtTiempoDeViaje = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jsFechaHora = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADMINISTRACION");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ADMINISTRACION COPETRAN");
        jLabel1.setToolTipText("");

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("REGISTRAR BUS:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Placa:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Tipo de Servicio:");

        cmdRegistrarBus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdRegistrarBus.setText("REGISTRAR BUS");
        cmdRegistrarBus.addActionListener(this::cmdRegistrarBusActionPerformed);

        cmbTipoServicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EJECUTIVO", "NORMAL" }));

        cmdRegistrarRuta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdRegistrarRuta.setText("REGISTRAR RUTA");
        cmdRegistrarRuta.addActionListener(this::cmdRegistrarRutaActionPerformed);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("REGISTRAR RUTA:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Destino:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("Tarifa Basica:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Fecha/Hora:");

        cmdRegistrarSalida.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdRegistrarSalida.setText("REGISTRAR SALIDA");
        cmdRegistrarSalida.addActionListener(this::cmdRegistrarSalidaActionPerformed);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("REGISTRAR SALIDA:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Bus:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setText("Ruta:");

        cmbElegirBus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione aqui..." }));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Conductor:");

        cmbConductorElegir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione aqui..." }));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("REGISTRAR CONDUCTOR:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Cedula:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Celular:");

        cmdRegistrarConductor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdRegistrarConductor.setText("REGISTRAR CONDUCTOR");
        cmdRegistrarConductor.addActionListener(this::cmdRegistrarConductorActionPerformed);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("E-mail:");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Años exp:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Sueldo:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("LISTAR:");

        cmbElegirRuta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione aqui..." }));

        cmdListar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdListar.setText("LISTAR");
        cmdListar.addActionListener(this::cmdListarActionPerformed);

        cmbListas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione aqui...", "CONDUCTOR", "BUS", "RUTA", "SALIDA" }));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("INFORMACION");

        cmdCambiarEstado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdCambiarEstado.setText("CAMBIAR ESTADO");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Tiempo viaje:");

        jsFechaHora.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(jLabel3)
                                .addGap(131, 131, 131))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel23)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel15))
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtPlaca)
                                                    .addComponent(cmbTipoServicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(cmbConductorElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jLabel2)
                                            .addComponent(cmdRegistrarConductor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cmdRegistrarBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmdCambiarEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel5))
                                                .addGap(43, 43, 43))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel21)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombreConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCedulaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCelularConductor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtCorreoConductor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtExp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmdRegistrarRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbElegirRuta, 0, 181, Short.MAX_VALUE)
                                    .addComponent(cmbElegirBus, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jsFechaHora)))
                            .addComponent(cmdRegistrarSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbListas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTiempoDeViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmdListar, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel12))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtDestino, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(0, 28, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel24))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTiempoDeViaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtNombreConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(txtCedulaConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(txtCelularConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cmdRegistrarRuta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmbElegirBus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbElegirRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(jsFechaHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(cmdRegistrarSalida)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cmbListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(cmdListar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(txtCorreoConductor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel22)
                                    .addComponent(txtExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel23))
                                .addGap(18, 18, 18)
                                .addComponent(cmdRegistrarConductor)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(cmbTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(cmbConductorElegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(cmdRegistrarBus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmdCambiarEstado)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdRegistrarBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarBusActionPerformed
        // TODO add your handling code here:
        String placa = this.txtPlaca.getText();
        String tipoBus = this.cmbTipoServicio.getSelectedItem().toString();
        String conductor = this.cmbConductorElegir.getSelectedItem().toString();
        
        if(this.cmbTipoServicio.getSelectedItem().equals("Seleccione aqui...")){
            txtMostrar.setText("DEBE SELECCIONAR UN TIPO DE SERVICIO");
        }
        if(this.cmbConductorElegir.getSelectedItem().equals("Seleccione aqui...")){
            txtMostrar.setText("DEBE SELECCIONAR UN CONDUCTOR");
        }
        
        String registroBus = this.myCopetran.registrarBusesCopetran(placa, tipoBus, conductor);
        this.txtMostrar.setText(registroBus);
        
        if (registroBus.contains("BUS REGISTRADO CON EXITO")){
            this.cargarBuses(this.myCopetran.placaBuses());
            this.txtPlaca.setText("");
        }
    }//GEN-LAST:event_cmdRegistrarBusActionPerformed

    private void cmdRegistrarRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarRutaActionPerformed
        // TODO add your handling code here:
        this.txtMostrar.setText("");
        String destino = this.txtDestino.getText().toUpperCase();
        int tarifa = Integer.parseInt(this.txtTarifa.getText());
        
        String registroRuta = this.myCopetran.registrarRutasCopetran(destino, tarifa);
        this.txtMostrar.setText(registroRuta);
        
        if(registroRuta.contains("RUTA REGISTRADA CON EXITO")){
            this.cargarRutas(this.myCopetran.destinoRutas());
            this.limpiarRuta();
        }
        
    }//GEN-LAST:event_cmdRegistrarRutaActionPerformed

    private void cmdRegistrarSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarSalidaActionPerformed
        // TODO add your handling code here:
        this.txtMostrar.setText("");
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/yyyy");
        String ruta = this.cmbElegirRuta.getSelectedItem().toString();
        String bus = this.cmbElegirBus.getSelectedItem().toString();
        java.util.Date fechaHora = (Date) jsFechaHora.getValue();
        
        if(this.cmbElegirRuta.getSelectedItem().equals("Seleccione aqui...")||this.cmbElegirBus.getSelectedItem().equals("Seleccione aqui...")){
            txtMostrar.setText("DEBE SELECCIONAR BUS Y RUTA");
        }
        
        String reporte = this.myCopetran.registrarSalidasCopetran(ruta, bus, fechaHora);
        this.txtMostrar.setText(reporte);
    }//GEN-LAST:event_cmdRegistrarSalidaActionPerformed

    private void cmdRegistrarConductorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarConductorActionPerformed
        // TODO add your handling code here:
        //String añosExperiencia, String nombre, String cedula, String celular, String correo, int sueldo
        this.txtMostrar.setText("");
        String nombre = this.txtNombreConductor.getText();
        String cc = this.txtCedulaConductor.getText();
        String cel = this.txtCelularConductor.getText();
        String correo = this.txtCorreoConductor.getText();
        String exp = this.txtExp.getText();
        int sueldo = Integer.parseInt(this.txtSueldo.getText());
        
        String reporte = this.myCopetran.conductorRegistro(nombre, cc, cel, exp, correo, sueldo);
        this.txtMostrar.setText(reporte);
        
        if(reporte.contains("CONDUCTOR REGISTRADO CON EXITO")){
            this.cargarConductores(this.myCopetran.nombresConductores());
            this.limpiarConductor();
        }
    }//GEN-LAST:event_cmdRegistrarConductorActionPerformed

    private void cmdListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdListarActionPerformed
        // TODO add your handling code here:
        if(this.cmbListas.getSelectedItem().equals("CONDUCTOR")){
            txtMostrar.setText(this.myCopetran.conductoresListado());
        }
        if(this.cmbListas.getSelectedItem().equals("BUS")){
            txtMostrar.setText(this.myCopetran.busesListado());
        }
        if(this.cmbListas.getSelectedItem().equals("RUTA")){
            txtMostrar.setText(this.myCopetran.rutasListado());
        }
        if(this.cmbListas.getSelectedItem().equals("SALIDA")){
            txtMostrar.setText(this.myCopetran.salidasListado());
        }
        if(this.cmbListas.getSelectedItem().equals("Seleccione aqui...")){
            txtMostrar.setText("DEBE SELECCIONAR ALGUNA DE LAS 4 OPCIONES");
        }
        
    }//GEN-LAST:event_cmdListarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbConductorElegir;
    private javax.swing.JComboBox<String> cmbElegirBus;
    private javax.swing.JComboBox<String> cmbElegirRuta;
    private javax.swing.JComboBox<String> cmbListas;
    private javax.swing.JComboBox<String> cmbTipoServicio;
    private javax.swing.JButton cmdCambiarEstado;
    private javax.swing.JButton cmdListar;
    private javax.swing.JButton cmdRegistrarBus;
    private javax.swing.JButton cmdRegistrarConductor;
    private javax.swing.JButton cmdRegistrarRuta;
    private javax.swing.JButton cmdRegistrarSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jsFechaHora;
    private javax.swing.JTextField txtCedulaConductor;
    private javax.swing.JTextField txtCelularConductor;
    private javax.swing.JTextField txtCorreoConductor;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtExp;
    private javax.swing.JTextArea txtMostrar;
    private javax.swing.JTextField txtNombreConductor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtTarifa;
    private javax.swing.JTextField txtTiempoDeViaje;
    // End of variables declaration//GEN-END:variables

    private void cargarBuses(ArrayList<String> placaBuses) {
        for (int i = 0; i < placaBuses.size(); i++) {
            cmbElegirBus.addItem(placaBuses.get(i));
        }
    }
    
    private void cargarRutas(ArrayList<String> destinoRutas) {
        for (int i = 0; i < destinoRutas.size(); i++) {
            cmbElegirRuta.addItem(destinoRutas.get(i));
        }
    }

    private void cargarConductores(ArrayList<String> nombresConductores) {
        for (int i = 0; i < nombresConductores.size(); i++) {
            cmbConductorElegir.addItem(nombresConductores.get(i));
        }
    }
    
    private void limpiarConductor(){
        this.txtCedulaConductor.setText("");
        this.txtNombreConductor.setText("");
        this.txtCorreoConductor.setText("");
        this.txtExp.setText("");
        this.txtSueldo.setText("");
        this.txtCelularConductor.setText("");
    }
    
    private void limpiarRuta(){
        this.txtDestino.setText("");
    }
}
