/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import Negocio.Copetran;
import java.util.ArrayList;

/**
 *
 * @author GAMEMAX
 */
public class FormCliente extends javax.swing.JFrame {
    
    private Copetran myCliente;

    /**
     * Creates new form FormCliente
     */
    public FormCliente(Copetran fc) {
        initComponents();
        this.myCliente = fc;
        cargarClientes(this.myCliente.nombresClientes());
        limpiarCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMostrar = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmdRegistrarCliente = new javax.swing.JButton();
        txtNombreCliente = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtGmailCliente = new javax.swing.JTextField();
        txtCedulaCliente = new javax.swing.JTextField();
        txtCelularCliente = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtMostrar1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        cmdPasajeroSeleccion = new javax.swing.JComboBox<>();
        cmbVentaPasaje = new javax.swing.JButton();
        cmbMostrarReporte = new javax.swing.JButton();

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel24.setText("INFORMACION");

        txtMostrar.setColumns(20);
        txtMostrar.setRows(5);
        jScrollPane1.setViewportView(txtMostrar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VENTAS CLIENTES");
        jLabel1.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("REGISTRAR CLIENTE:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Cedula:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Celular:");

        cmdRegistrarCliente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdRegistrarCliente.setText("REGISTRAR CLIENTE");
        cmdRegistrarCliente.addActionListener(this::cmdRegistrarClienteActionPerformed);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("E-mail:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel25.setText("INFORMACION");

        txtMostrar1.setColumns(20);
        txtMostrar1.setRows(5);
        jScrollPane2.setViewportView(txtMostrar1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("VENTA DE PASAJE:");

        cmdPasajeroSeleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un pasajero..." }));

        cmbVentaPasaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbVentaPasaje.setText("IR A VENTA DE PASAJES");
        cmbVentaPasaje.addActionListener(this::cmbVentaPasajeActionPerformed);

        cmbMostrarReporte.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbMostrarReporte.setText("MOSTRAR REPORTE DE VENTAS POR RUTA");
        cmbMostrarReporte.addActionListener(this::cmbMostrarReporteActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(cmdRegistrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel5))
                                .addGap(43, 43, 43))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtGmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addComponent(cmdPasajeroSeleccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbVentaPasaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbMostrarReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtCelularCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtGmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdRegistrarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmdPasajeroSeleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbVentaPasaje)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbMostrarReporte))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistrarClienteActionPerformed
        // TODO add your handling code here:
        //String añosExperiencia, String nombre, String cedula, String celular, String correo, int sueldo
        this.txtMostrar1.setText("");
        String nombre = this.txtNombreCliente.getText();
        String cedula = this.txtCedulaCliente.getText();
        String celular = this.txtCelularCliente.getText();
        String correo = this.txtGmailCliente.getText();
        condicionarClienteRegistro();
        String registroCliente = this.myCliente.clienteRegistro(nombre, cedula, celular, correo);
        this.txtMostrar1.setText(registroCliente);
        
        if(registroCliente.contains("CLIENTE REGISTRADO CON EXITO")){
            cargarClientes(this.myCliente.nombresClientes());
            this.limpiarCliente();
        }
    }//GEN-LAST:event_cmdRegistrarClienteActionPerformed

    private void cmbVentaPasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVentaPasajeActionPerformed
        // TODO add your handling code here:
        String clienteSeleccionado =  cmdPasajeroSeleccion.getSelectedItem().toString();
        FormVenta myCuar = new FormVenta(this.myCliente,clienteSeleccionado);
        myCuar.setVisible(true);
    }//GEN-LAST:event_cmbVentaPasajeActionPerformed

    private void cmbMostrarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMostrarReporteActionPerformed
        // TODO add your handling code here:
        String reporteFinal = this.myCliente.generarReporteRutaDiaria();
        txtMostrar1.setText(reporteFinal);
    }//GEN-LAST:event_cmbMostrarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbMostrarReporte;
    private javax.swing.JButton cmbVentaPasaje;
    private javax.swing.JComboBox<String> cmdPasajeroSeleccion;
    private javax.swing.JButton cmdRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtCelularCliente;
    private javax.swing.JTextField txtGmailCliente;
    private javax.swing.JTextArea txtMostrar;
    private javax.swing.JTextArea txtMostrar1;
    private javax.swing.JTextField txtNombreCliente;
    // End of variables declaration//GEN-END:variables

    private void cargarClientes(ArrayList<String> nombresClientes) {
        this.cmdPasajeroSeleccion.removeAllItems();
        this.cmdPasajeroSeleccion.addItem("Seleccione aqui...");
        for (int i = 0; i < nombresClientes.size(); i++) {
            cmdPasajeroSeleccion.addItem(nombresClientes.get(i));
        }
    }

    private void limpiarCliente() {
        this.txtCedulaCliente.setText("");
        this.txtGmailCliente.setText("");
        this.txtCelularCliente.setText("");
        this.txtNombreCliente.setText("");
    }
    private void condicionarClienteRegistro(){
        if(this.txtNombreCliente.getText().isEmpty() || this.txtCedulaCliente.getText().isEmpty()
            || this.txtCelularCliente.getText().isEmpty() ||  this.txtGmailCliente.getText().isEmpty()){
            
            this.txtMostrar.setText("TODOS LOS CAMPOS SON NECESARIOS");
        }
        
    }
}
